name = "Trevor Drozd"
description = "description"
keywords = "key, words, comma, separated"
image = "me.jpeg"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = ""
base_url = "https://TcDrozd.github.io"

[[sections]]
title = "Section Title"
description = "Here are some of my items"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Item 1"
description = "Description of Item 1"
url = "https://tcdrozd.github.io"
[[sections.items]]
title = "Item 2"
description = "Description of Item 2"
url = "https://tcdrozd.github.io"
[[sections.items]]
title = "Item 3"
description = "Description of Item 3"
url = "https://tcdrozd.github.io"

[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/jakegyllenhaal"
[[sections.items]]
title = "IMDb"
url = "https://www.imdb.com/name/nm0350453/"
[[sections.items]]
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
[[sections.items]]
title = "Rotten Tomatoes"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
